In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\Smart\Desktop\Mental Health Prediction from Survey Data\dataset\survey (1).csv')

In [3]:
df

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [5]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [6]:
df.iloc[:,9:18]

,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave
0,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy
1,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know
2,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult
3,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult
4,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know
...,...,...,...,...,...,...,...,...,...
1254,26-100,No,Yes,No,No,No,No,Don't know,Somewhat easy
1255,26-100,Yes,Yes,Yes,Yes,No,No,Yes,Somewhat difficult
1256,More than 1000,No,Yes,Yes,Yes,No,No,Don't know,Somewhat difficult
1257,100-500,Yes,Yes,No,Yes,No,No,Don't know,Don't know
1258,26-100,No,No,Yes,Yes,No,No,Yes,Don't know

In [7]:
df['seek_help'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [8]:
df.drop(columns=['Timestamp','state','comments'],axis=1,inplace=True)

In [9]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,United Kingdom,No,No,Yes,NaN,26-100,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,United States,No,Yes,Yes,Sometimes,More than 1000,No,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,f,United States,No,No,No,NaN,100-500,Yes,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [10]:
df['self_employed'].fillna(df['self_employed'].mode()[0],inplace=True)

In [11]:
df['family_history'].fillna(df['self_employed'].mode()[0],inplace=True)

In [12]:
df['work_interfere'].fillna(df['self_employed'].mode()[0],inplace=True)

In [13]:
df.isnull().sum()

Age                          0
Gender                       0
Country                      0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [14]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,No,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,No,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,No,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,No,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,No,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,United Kingdom,No,No,Yes,No,26-100,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,United States,No,Yes,Yes,Sometimes,More than 1000,No,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,f,United States,No,No,No,No,100-500,Yes,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [15]:
df['Gender'].unique()

array(['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile',
       'Trans-female', 'Cis Female', 'F', 'something kinda male?',
       'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they',
       'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'All', 'Enby',
       'fluid', 'Genderqueer', 'Female ', 'Androgyne', 'Agender',
       'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous',
       'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)',
       'queer', 'Female (cis)', 'Mail', 'cis male', 'A little about you',
       'Malr', 'p', 'femail', 'Cis Man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [16]:
df['Gender'].str.lower().unique()

array(['female', 'm', 'male', 'male-ish', 'maile', 'trans-female',
       'cis female', 'f', 'something kinda male?', 'cis male', 'woman',
       'mal', 'male (cis)', 'queer/she/they', 'non-binary', 'femake',
       'make', 'nah', 'all', 'enby', 'fluid', 'genderqueer', 'female ',
       'androgyne', 'agender', 'cis-female/femme', 'guy (-ish) ^_^',
       'male leaning androgynous', 'male ', 'man', 'trans woman', 'msle',
       'neuter', 'female (trans)', 'queer', 'female (cis)', 'mail',
       'a little about you', 'malr', 'p', 'femail', 'cis man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [17]:
df['Gender'].str.lower().str.strip().unique()

array(['female', 'm', 'male', 'male-ish', 'maile', 'trans-female',
       'cis female', 'f', 'something kinda male?', 'cis male', 'woman',
       'mal', 'male (cis)', 'queer/she/they', 'non-binary', 'femake',
       'make', 'nah', 'all', 'enby', 'fluid', 'genderqueer', 'androgyne',
       'agender', 'cis-female/femme', 'guy (-ish) ^_^',
       'male leaning androgynous', 'man', 'trans woman', 'msle', 'neuter',
       'female (trans)', 'queer', 'female (cis)', 'mail',
       'a little about you', 'malr', 'p', 'femail', 'cis man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [18]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [19]:
df['Gender'].unique()

array(['female', 'm', 'male', 'male-ish', 'maile', 'trans-female',
       'cis female', 'f', 'something kinda male?', 'cis male', 'woman',
       'mal', 'male (cis)', 'queer/she/they', 'non-binary', 'femake',
       'make', 'nah', 'all', 'enby', 'fluid', 'genderqueer', 'androgyne',
       'agender', 'cis-female/femme', 'guy (-ish) ^_^',
       'male leaning androgynous', 'man', 'trans woman', 'msle', 'neuter',
       'female (trans)', 'queer', 'female (cis)', 'mail',
       'a little about you', 'malr', 'p', 'femail', 'cis man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [20]:
def clean_gender(gender):
    gender = gender.lower().strip()

    malekeywords = ['m','male','male-ish','maile','something kinda male?','cis male','mal','male (cis)','make','guy (-ish) ^_^','male leaning androgynous','man','msle','mail','malr','cis man','ostensibly male, unsure what that really means']
    femalekeywords = ['female','cis female','f','woman','queer/she/they','femake','cis-female/femme','female (cis)','femail']
    transkeywords = ['trans-female','trans woman','female (trans)','all']
    nonbinarykeywords = ['non-binary','nah','enby','fluid','genderqueer','androgyne','agender','neuter','queer','p','a little about']

    for word in malekeywords:
        if word in gender:
            return "Male"
    
    for word in femalekeywords:
        if word in gender:
            return "Female"
        
    for word in transkeywords:
        if word in gender:
            return 'Transgender'
        
    for word in nonbinarykeywords:
        if word in gender:
            return 'Non Binary'

In [21]:
df['Gender'] = df['Gender'].apply(clean_gender)

In [22]:
df['Gender'].unique()

array(['Male', 'Female', 'Non Binary', 'Transgender'], dtype=object)

In [23]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Male,United States,No,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,Male,United States,No,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,No,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,No,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,No,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,Male,United Kingdom,No,No,Yes,No,26-100,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,Male,United States,No,Yes,Yes,Sometimes,More than 1000,No,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,Female,United States,No,No,No,No,100-500,Yes,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [24]:
df['work_interfere'].unique()

array(['Often', 'Rarely', 'Never', 'Sometimes', 'No'], dtype=object)

In [25]:
wi_column_mapping = {
    'Never':0,
    'No':0,
    'Sometimes':1,
    'Rarely':1,
    'Often':2
}

df['work_interfere'] = df['work_interfere'].map(wi_column_mapping)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1259 non-null   int64
 1   Gender                     1259 non-null   object
 2   Country                    1259 non-null   object
 3   self_employed              1259 non-null   object
 4   family_history             1259 non-null   object
 5   treatment                  1259 non-null   object
 6   work_interfere             1259 non-null   int64
 7   no_employees               1259 non-null   object
 8   remote_work                1259 non-null   object
 9   tech_company               1259 non-null   object
 10  benefits                   1259 non-null   object
 11  care_options               1259 non-null   object
 12  wellness_program           1259 non-null   object
 13  seek_help                  1259 non-null   object
 14  anonymity                  1259 non-null   object
 15  leave                      1259 non-null   object
 16  mental_health_consequence  1259 non-null   object
 17  phys_health_consequence    1259 non-null   object
 18  coworkers                  1259 non-null   object
 19  supervisor                 1259 non-null   object
 20  mental_health_interview    1259 non-null   object
 21  phys_health_interview      1259 non-null   object
 22  mental_vs_physical         1259 non-null   object
 23  obs_consequence            1259 non-null   object
dtypes: int64(2), object(22)
memory usage: 236.2+ KB

In [27]:
df['anonymity'].unique()

array(['Yes', "Don't know", 'No'], dtype=object)

In [28]:
yes_no_donttknow_mapping = {
    'Yes':0,
    'No':1,
    "Don't know":2,
}

df['anonymity'] = df['anonymity'].map(yes_no_donttknow_mapping)
df['benefits'] = df['benefits'].map(yes_no_donttknow_mapping)
df['wellness_program'] = df['wellness_program'].map(yes_no_donttknow_mapping)
df['seek_help'] = df['seek_help'].map(yes_no_donttknow_mapping)
df['mental_vs_physical'] = df['mental_vs_physical'].map(yes_no_donttknow_mapping)

In [29]:
df['benefits'].unique()

array([0, 2, 1], dtype=int64)

In [30]:
df['care_options'].unique()

array(['Not sure', 'No', 'Yes'], dtype=object)

In [31]:
yes_no_donttknow_mapping = {
    'Yes':0,
    'No':1,
    "Not sure":2,
}

df['care_options'] = df['care_options'].map(yes_no_donttknow_mapping)

In [32]:
yes_no_donttknow_mapping = {
    'Yes':0,
    'No':1,
    "Maybe":2,
}

df['mental_health_consequence'] = df['mental_health_consequence'].map(yes_no_donttknow_mapping)
df['phys_health_consequence'] = df['phys_health_consequence'].map(yes_no_donttknow_mapping)
df['mental_health_interview'] = df['mental_health_interview'].map(yes_no_donttknow_mapping)
df['phys_health_interview'] = df['phys_health_interview'].map(yes_no_donttknow_mapping)

In [33]:
df['wellness_program'].unique()

array([1, 2, 0], dtype=int64)

In [34]:
df['seek_help'].unique()

array([0, 2, 1], dtype=int64)

In [35]:
df['leave'].unique()

array(['Somewhat easy', "Don't know", 'Somewhat difficult',
       'Very difficult', 'Very easy'], dtype=object)

In [36]:
yes_no_donttknow_mapping = {
    'Very easy':0,
    'Somewhat easy':1,
    "Somewhat difficult":2,
    'Very difficult':3,
    "Don't know":4,
}
df['leave'] = df['leave'].map(yes_no_donttknow_mapping)

In [37]:
df['mental_health_consequence'].unique()

array([1, 2, 0], dtype=int64)

In [38]:
df['phys_health_consequence'].unique()

array([1, 0, 2], dtype=int64)

In [39]:
df['coworkers'].unique()

array(['Some of them', 'No', 'Yes'], dtype=object)

In [40]:
yes_no_donttknow_mapping = {
    'Yes':0,
    'No':1,
    "Some of them":2,
}

df['coworkers'] = df['coworkers'].map(yes_no_donttknow_mapping)
df['supervisor'] = df['supervisor'].map(yes_no_donttknow_mapping)

In [41]:
df['supervisor'].unique()

array([0, 1, 2], dtype=int64)

In [42]:
df['mental_health_interview'].unique()

array([1, 0, 2], dtype=int64)

In [43]:
df['phys_health_interview'].unique()

array([2, 1, 0], dtype=int64)

In [44]:
df['mental_vs_physical'].unique()

array([0, 2, 1], dtype=int64)

In [45]:
df['obs_consequence'].unique()

array(['No', 'Yes'], dtype=object)

In [46]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Male,United States,No,No,Yes,2,6-25,No,Yes,...,0,1,1,1,2,0,1,2,0,No
1,44,Male,United States,No,No,No,1,More than 1000,No,No,...,2,4,2,1,1,1,1,1,2,No
2,32,Male,Canada,No,No,No,1,6-25,No,Yes,...,2,2,1,1,0,0,0,0,1,No
3,31,Male,United Kingdom,No,Yes,Yes,2,26-100,No,Yes,...,1,2,0,0,2,1,2,2,1,Yes
4,31,Male,United States,No,No,No,0,100-500,Yes,Yes,...,2,4,1,1,2,0,0,0,2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,Male,United Kingdom,No,No,Yes,0,26-100,No,Yes,...,2,1,1,1,2,2,1,1,2,No
1255,32,Male,United States,No,Yes,Yes,2,26-100,Yes,Yes,...,0,2,1,1,2,0,1,1,0,No
1256,34,Male,United States,No,Yes,Yes,1,More than 1000,No,Yes,...,2,2,0,0,1,1,1,1,1,No
1257,46,Female,United States,No,No,No,0,100-500,Yes,Yes,...,2,4,0,1,1,1,1,1,1,No
1258,25,Male,United States,No,Yes,Yes,1,26-100,No,No,...,0,4,2,1,2,1,1,1,2,No

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1259 non-null   int64
 1   Gender                     1259 non-null   object
 2   Country                    1259 non-null   object
 3   self_employed              1259 non-null   object
 4   family_history             1259 non-null   object
 5   treatment                  1259 non-null   object
 6   work_interfere             1259 non-null   int64
 7   no_employees               1259 non-null   object
 8   remote_work                1259 non-null   object
 9   tech_company               1259 non-null   object
 10  benefits                   1259 non-null   int64
 11  care_options               1259 non-null   int64
 12  wellness_program           1259 non-null   int64
 13  seek_help                  1259 non-null   int64
 14  anonymity                  1259 non-null   int64
 15  leave                      1259 non-null   int64
 16  mental_health_consequence  1259 non-null   int64
 17  phys_health_consequence    1259 non-null   int64
 18  coworkers                  1259 non-null   int64
 19  supervisor                 1259 non-null   int64
 20  mental_health_interview    1259 non-null   int64
 21  phys_health_interview      1259 non-null   int64
 22  mental_vs_physical         1259 non-null   int64
 23  obs_consequence            1259 non-null   object
dtypes: int64(15), object(9)
memory usage: 236.2+ KB

In [48]:
yes_no_mapping = {
    'Yes':0,
    'No':1
}

df['self_employed'] = df['self_employed'].map(yes_no_mapping)
df['family_history'] = df['family_history'].map(yes_no_mapping)
df['treatment'] = df['treatment'].map(yes_no_mapping)
df['remote_work'] = df['remote_work'].map(yes_no_mapping)
df['tech_company'] = df['tech_company'].map(yes_no_mapping)
df['obs_consequence'] = df['obs_consequence'].map(yes_no_mapping)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1259 non-null   int64
 1   Gender                     1259 non-null   object
 2   Country                    1259 non-null   object
 3   self_employed              1259 non-null   int64
 4   family_history             1259 non-null   int64
 5   treatment                  1259 non-null   int64
 6   work_interfere             1259 non-null   int64
 7   no_employees               1259 non-null   object
 8   remote_work                1259 non-null   int64
 9   tech_company               1259 non-null   int64
 10  benefits                   1259 non-null   int64
 11  care_options               1259 non-null   int64
 12  wellness_program           1259 non-null   int64
 13  seek_help                  1259 non-null   int64
 14  anonymity                  1259 non-null   int64
 15  leave                      1259 non-null   int64
 16  mental_health_consequence  1259 non-null   int64
 17  phys_health_consequence    1259 non-null   int64
 18  coworkers                  1259 non-null   int64
 19  supervisor                 1259 non-null   int64
 20  mental_health_interview    1259 non-null   int64
 21  phys_health_interview      1259 non-null   int64
 22  mental_vs_physical         1259 non-null   int64
 23  obs_consequence            1259 non-null   int64
dtypes: int64(21), object(3)
memory usage: 236.2+ KB

In [50]:
df['Gender'].unique()

array(['Male', 'Female', 'Non Binary', 'Transgender'], dtype=object)

In [51]:
gender_mapping = {
    'Male':0,
    'Female':1,
    'Transgender':2,
    'Non Binary':3
}

df['Gender'] = df['Gender'].map(gender_mapping)

In [52]:
df['Gender'].unique()

array([0, 1, 3, 2], dtype=int64)

In [53]:
df['no_employees'].unique()

array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
      dtype=object)

In [54]:
employee_map = {
    '1-5': 0,
    '6-25': 1,
    '26-100': 2,
    '100-500': 3,
    '500-1000': 4,
    'More than 1000': 5
}

df['no_employees'] = df['no_employees'].map(employee_map)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1259 non-null   int64
 1   Gender                     1259 non-null   int64
 2   Country                    1259 non-null   object
 3   self_employed              1259 non-null   int64
 4   family_history             1259 non-null   int64
 5   treatment                  1259 non-null   int64
 6   work_interfere             1259 non-null   int64
 7   no_employees               1259 non-null   int64
 8   remote_work                1259 non-null   int64
 9   tech_company               1259 non-null   int64
 10  benefits                   1259 non-null   int64
 11  care_options               1259 non-null   int64
 12  wellness_program           1259 non-null   int64
 13  seek_help                  1259 non-null   int64
 14  anonymity                  1259 non-null   int64
 15  leave                      1259 non-null   int64
 16  mental_health_consequence  1259 non-null   int64
 17  phys_health_consequence    1259 non-null   int64
 18  coworkers                  1259 non-null   int64
 19  supervisor                 1259 non-null   int64
 20  mental_health_interview    1259 non-null   int64
 21  phys_health_interview      1259 non-null   int64
 22  mental_vs_physical         1259 non-null   int64
 23  obs_consequence            1259 non-null   int64
dtypes: int64(23), object(1)
memory usage: 236.2+ KB

In [56]:
df['Country'].unique()

array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
       'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
       'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
       'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
       'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
       'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
       'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
       'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
       'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China',
       'Czech Republic', 'Philippines'], dtype=object)

In [57]:
df['Country'] = df['Country'].replace({'Bahamas, The': 'The Bahamas'})

In [58]:
df['Country'].unique()

array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
       'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
       'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
       'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
       'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
       'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
       'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
       'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
       'The Bahamas', 'Greece', 'Moldova', 'Georgia', 'China',
       'Czech Republic', 'Philippines'], dtype=object)

In [59]:
# import sys
# !{sys.executable} -m pip install category_encoders

In [60]:
from category_encoders import TargetEncoder

In [61]:
encoder = TargetEncoder()
df['Country'] = encoder.fit_transform(df['Country'],df['treatment'])

In [62]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,0,0.454061,1,1,0,2,1,1,0,...,0,1,1,1,2,0,1,2,0,1
1,44,0,0.454061,1,1,1,1,5,1,1,...,2,4,2,1,1,1,1,1,2,1
2,32,0,0.486155,1,1,1,1,1,1,0,...,2,2,1,1,0,0,0,0,1,1
3,31,0,0.497297,1,0,0,2,2,1,0,...,1,2,0,0,2,1,2,2,1,0
4,31,0,0.454061,1,1,1,0,3,0,0,...,2,4,1,1,2,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,0,0.497297,1,1,0,0,2,1,0,...,2,1,1,1,2,2,1,1,2,1
1255,32,0,0.454061,1,0,0,2,2,0,0,...,0,2,1,1,2,0,1,1,0,1
1256,34,0,0.454061,1,0,0,1,5,1,0,...,2,2,0,0,1,1,1,1,1,1
1257,46,1,0.454061,1,1,1,0,3,0,0,...,2,4,0,1,1,1,1,1,1,1
1258,25,0,0.454061,1,0,0,1,2,1,1,...,0,4,2,1,2,1,1,1,2,1

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1259 non-null   int64
 1   Gender                     1259 non-null   int64
 2   Country                    1259 non-null   float64
 3   self_employed              1259 non-null   int64
 4   family_history             1259 non-null   int64
 5   treatment                  1259 non-null   int64
 6   work_interfere             1259 non-null   int64
 7   no_employees               1259 non-null   int64
 8   remote_work                1259 non-null   int64
 9   tech_company               1259 non-null   int64
 10  benefits                   1259 non-null   int64
 11  care_options               1259 non-null   int64
 12  wellness_program           1259 non-null   int64
 13  seek_help                  1259 non-null   int64
 14  anonymity                  1259 non-null   int64
 15  leave                      1259 non-null   int64
 16  mental_health_consequence  1259 non-null   int64
 17  phys_health_consequence    1259 non-null   int64
 18  coworkers                  1259 non-null   int64
 19  supervisor                 1259 non-null   int64
 20  mental_health_interview    1259 non-null   int64
 21  phys_health_interview      1259 non-null   int64
 22  mental_vs_physical         1259 non-null   int64
 23  obs_consequence            1259 non-null   int64
dtypes: float64(1), int64(23)
memory usage: 236.2 KB

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x = df.drop(columns=['treatment'],axis = 1)
y = df['treatment']

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [69]:
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [70]:
y_pred = model.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score, classification_report

In [72]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8134920634920635
              precision    recall  f1-score   support

           0       0.78      0.85      0.82       123
           1       0.85      0.78      0.81       129

    accuracy                           0.81       252
   macro avg       0.82      0.81      0.81       252
weighted avg       0.82      0.81      0.81       252

In [73]:
import joblib
joblib.dump(model, 'mental_health_model.pkl')

['mental_health_model.pkl']

In [74]:
#html pages varche options nit kara 
#je je dataset madhe options ahet te te html madhe add kara(jashe encode kele aahet tassch)

In [77]:
joblib.dump(encoder, 'country_encoder.pkl')

['country_encoder.pkl']

In [76]:
#chat gpt var latest updates code aahe to run karun bagh hotay ki nahi te

In [78]:
df

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,0,0.454061,1,1,0,2,1,1,0,...,0,1,1,1,2,0,1,2,0,1
1,44,0,0.454061,1,1,1,1,5,1,1,...,2,4,2,1,1,1,1,1,2,1
2,32,0,0.486155,1,1,1,1,1,1,0,...,2,2,1,1,0,0,0,0,1,1
3,31,0,0.497297,1,0,0,2,2,1,0,...,1,2,0,0,2,1,2,2,1,0
4,31,0,0.454061,1,1,1,0,3,0,0,...,2,4,1,1,2,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,0,0.497297,1,1,0,0,2,1,0,...,2,1,1,1,2,2,1,1,2,1
1255,32,0,0.454061,1,0,0,2,2,0,0,...,0,2,1,1,2,0,1,1,0,1
1256,34,0,0.454061,1,0,0,1,5,1,0,...,2,2,0,0,1,1,1,1,1,1
1257,46,1,0.454061,1,1,1,0,3,0,0,...,2,4,0,1,1,1,1,1,1,1
1258,25,0,0.454061,1,0,0,1,2,1,1,...,0,4,2,1,2,1,1,1,2,1

In [79]:
model.predict([[21,0,0.454061,1,1,1,1,1,0,2,1,1,2,0,2,0,0,1,1,1,1,0,0]])

c:\Users\Smart\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)